name: "Set AWS Params in AB2D Account"
description: "Composite action to set environment variables from AWS parameters in AB2D account"
inputs:
  aws_region:
    description: "AWS region to use"
    required: true
    default: 'us-east-1'
  environment:
    description: "AB2D environment"
    required: true
    type: choice
    options:
      - dev
      - test
      - sandbox
      - prod
runs:
  using: "composite"
  steps:
    - name: Set env vars from AWS params in AB2D account
      uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        MODULE_DB_PREFIX: /ab2d/${{ inputs.environment }}/core
      with:
        params: |
          DB_ENDPOINT=${{ env.MODULE_DB_PREFIX }}/nonsensitive/writer_endpoint
          PGUSER=${{ env.MODULE_DB_PREFIX }}/sensitive/database_user
          PGPASSWORD=${{ env.MODULE_DB_PREFIX }}/sensitive/database_password

    - name: Add PG environment variables
      shell: bash
      run: |
        if [ ${{ inputs.environment }} == "test" ]; then
          PGDATABASE='impl'
        elif [ ${{ inputs.environment }} == "sandbox" ]; then
          PGDATABASE='sbx'
        else 
          PGDATABASE='${{ inputs.environment }}'
        fi
        
        PGHOST=$(echo $DB_ENDPOINT | cut -d ":" -f1)
        PGPORT=$(echo $DB_ENDPOINT | cut -d ":" -f2)
        echo "PGHOST=$PGHOST" >> $GITHUB_ENV
        echo "PGPORT=$PGPORT" >> $GITHUB_ENV
        echo "PGDATABASE=$PGDATABASE" >> $GITHUB_ENV
        echo "DATABASE_SCHEMA_NAME=ab2d" >> $GITHUB_ENV
        echo "PGSSLMODE=require" >> $GITHUB_ENV
