name: opt-out-import prod deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    environment: prod
    steps:
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/ab2d-prod-github-actions
      - name: Promote lambda code from test to prod
        run: |
          aws s3 cp --no-progress \
            s3://ab2d-test-opt-out-import-function/function-${{ github.sha }}.zip \
            s3://ab2d-prod-opt-out-import-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name ab2d-prod-opt-out-import \
            --s3-bucket ab2d-prod-opt-out-import-function --s3-key function-${{ github.sha }}.zip
