env:
  global:
  - secure: OY3JWzy8JxPXXqT/YOnYcwFGm46DgQdGMV5dkhDjrBeKgfb2H7ohY6GkAStQv8vV6LE/yu3N6f+XGuPwH2q27Q3I8daYeNY2MtGMt+wokkqhkJWG/XdqQodr+RbkUYN7BHiYQC6ZQKdh9NIA4JIWsNdh8TKrc7cFxy4WM5ACGO9pf6y96GRVT1CHIlwaYzXna+dE0Khbg3EGSa0tcEwLUmYdPGwK+6hiMeX0wTbhDr4YEh5kdnIAFuDDfj+KKmT9FJeTJXywFc9I6YuuYLL+z1g4GMAWCV7PoZdBOLVZQXzP/A8IE1jN7bSNean2risBRXi+PBKohZuvjpLb4UbTTp1+HR5FzPCKpkNvkLmyHpqaDCbDXfXSzMEwWxbj/6vmDK+hO5fqZrI/iO0rNugixxOKEl/ZPXga2Zf1nVxEGzfI86BVNHMegSL1AfLJ5kI+P/0HGnUBbnSAD/kH8k8Rd7r/PHCqoN7VwUhuirI5C9Ulbd6iMm1C8sgq7lOogJvVoS939lP3IcrtNhqmS3Wyc2YsWUE3RlIiJizOQB4K925el41o8qQmDvxIbB8tiDaqfkas3OjDVCr+JjzczXHgjV6Uze5EQovIQ4SvgNidZkjNyei+piJ+lwHx/34jBAC4GNs7uFgkA+RTrNtZCyHK2f2lv7OyNNzWyC3XMRIyQsM=
  - codeclimate: true
  - DOCKER_COMPOSE_VERSION: 1.24.1
  - secure: h8p+gMxYmKLZYrXrd1V3t8WSvrGjiFN2SmYsdQjgtZrZ5Hqm/IY0X18PF70/5nSNxc3h6JF0tfpkANmfdTJEFIF4PNccWpqfhsZc7axR691/pK0ky4kL7xWPVzAs5PP5JdkU2dDfibvb3KFw6sGZYfUdRhDRzFb5cUcNff+qgg0P1A3PRG07MplwUhtB0Xl9gdImaUmqW86kTXmISMpcTJ4bko9KRkX/3dp75B/NvLJqlh0KMaH2T0YtcM49MUPKuSmQOD16huWdZqmzOLN7XJ/rZk6kGWNeyK6yLhy9sd4sNcLZmn8ejxrjfVC1/lHNGRMXvd6oRKBLWK5E2KwYoyMi514t4oTLNA7I1Y44OIq9QE059d81Y+qbcU0eqOXS5MxBZdX7FTVKhH7hirhz+eD0tQIbcvJEhxQL6gWaQuyPgVudsAl6yDwwnSdIUJzdUV9Ri8HTJTAB8zi/sFUIf/aM/8CTzq38I2OJ8SdxQ+n+cd64RIMOSb2qJuI4TWZNudictpHl6f/rVPohpDz+vis1p1HixmfTI5mGl9llgT3U6zqqlcZPXDVkZBCRgf+gbdlB5YnFImU8n/N6RVTmfRFGQMybbDORM6ltZX+Ao913L88FpwTfpTkfb/tqfqD5mwWMtESHxGtVTYZug9+tYk+fUEySSWO01JTvtsj/NAM=
  - secure: n1NNXk+OkWTys5pLxwH+o1m0LT53HYBMxJz0negjampyLjPg0xPhdnGqdFITejHQ/fUYDdAFfkoJ/2sX2EZppya8B+X8YovqfxVms2F18e3/3zQhutmw3vxFgVuy/Lp5NkzQYDVoggzQOPNLfSJrCCSIo2FVdaKNjLnjCx3V1IFPq2HzFuUoFNliOpgiox6PICgg0HSysifRjhZygnSnlS0t7yTs5F3hipmPyQOhdyos/f7ut0x0ugW6cENDL8Bk+nR2znXzLqsdC6Y/+xjrpOubTdhQQyOHGTgdsHFTYSgfqBgTNiMzh8OorKfHs1gALnGjUtd4zzJg7lXqnHCkAM8RlFGg1aq7AMxLvuNYz+q84xNIfAxdpRjU2xukdMFke0+c2wR4x2eJHit691wMcezoaiJ5py7D3slmsdhEzyWLNOd86fWPpbebS7S18/p9kOwFpvS73YhGPKD/8M7ot/k78ota/2prBRih94RknXYnDj49HGLLzJu5UbXwf/juLdJK4t3ItapsmHef7hoZnrsPt9Nj0ZkWDI1ePVremFfQWbNGBPwIh/mQ4P+V44FAn3gkAjyPkklgC9slpfqZ254djsfejmMCc2QZTqVzJ1lMxrjxU0K1leVQNnvJFDafWgfVTIguhlgeLW7CC1IXB8bp3aJTp0GnbwikExVPOWs=
dist: bionic
language: java
jdk:
- openjdk13
cache:
  directories:
  - "$HOME/.m2"
before_install:
- mkdir -p /tmp/ab2d_efs_mount
- openssl aes-256-cbc -K $encrypted_27e3c48779c8_key -iv $encrypted_27e3c48779c8_iv
  -in ab2d_dev_keystore.enc -out /tmp/ab2d_efs_mount/ab2d_dev_keystore -d
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose version
- export OKTA_CLIENT_ID=0oa2t0lsrdZw5uWRx297
- export OKTA_CLIENT_PASSWORD=HHduWG6LogIvDIQuWgp3Zlo9OYMValTtH5OBcuHw
- export SECONDARY_USER_OKTA_CLIENT_ID=0oa2t0lc65ErV8OmY297
- export SECONDARY_USER_OKTA_CLIENT_PASSWORD=1Bl3HGO6eglkXUDtjVjto3L-3C0offzTMk2qlz9r
install: true
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- mvn clean verify
after_script:
- export JACOCO_SOURCE_PATH=./api/src/main/java; ./cc-test-reporter format-coverage
  ./api/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.api.json
- export JACOCO_SOURCE_PATH=./audit/src/main/java; ./cc-test-reporter format-coverage
  ./audit/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.audit.json
- export JACOCO_SOURCE_PATH=./common/src/main/java; ./cc-test-reporter format-coverage
  ./common/jacoco/jacoco.xml --input-type jacoco -o codeclimate.common.json
- export JACOCO_SOURCE_PATH=./filter/src/main/java; ./cc-test-reporter format-coverage
  ./filter/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.filter.json
- export JACOCO_SOURCE_PATH=./hpms/src/main/java; ./cc-test-reporter format-coverage
  ./hpms/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.hpms.json
- export JACOCO_SOURCE_PATH=./optout/src/main/java; ./cc-test-reporter format-coverage
  ./optout/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.optout.json
- export JACOCO_SOURCE_PATH=./bfd/src/main/java; ./cc-test-reporter format-coverage
  ./bfd/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.bfd.json
- export JACOCO_SOURCE_PATH=./worker/src/main/java; ./cc-test-reporter format-coverage
  ./worker/target/site/jacoco/jacoco.xml --input-type jacoco -o codeclimate.worker.json
- "./cc-test-reporter sum-coverage codeclimate.*.json -o coverage/codeclimate.json"
- if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
