version: '2.4'

##################
# Overrides specific properties of original compose for CI environment
# * Changes user from root to Jenkins to prevent issues with file permissions on server
# * Forces api and worker to wait for the postgres database to fully initialize before querying
# * Overrides the directory tmp-volume maps to on the file system with an environment variable because each branch
#   in Jenkins has a separate directory and must be isolated from other concurrently running jobs on the file system
##################

services:

  build:
    user: "${JENKINS_UID}:${JENKINS_GID}"

  api:
    user: "${JENKINS_UID}:${JENKINS_GID}"

  worker:
    user: "${JENKINS_UID}:${JENKINS_GID}"

# Override directory on machine which is the main volume mapped into each containers
volumes:
  tmp-volume:
    driver: local
    driver_opts:
      type: none
      device: ${AB2D_HOME}
      o: bind
