variable "env" {}
variable "vpc_id" {}
variable "public_subnet_ids" {}
variable "ami_id" {}
variable "instance_type" {}
variable "linux_user" {}
variable "ssh_key_name" {}
variable "iam_instance_profile" {}
variable "gold_disk_name" {}
variable "deployer_ip_address" {}