CREATE TABLE IF NOT EXISTS public.current_mbi (mbi VARCHAR(32) NOT NULL);
CREATE UNIQUE INDEX  IF NOT EXISTS unique_mbi ON public.current_mbi(mbi);

-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_anthem_united WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_bcbs WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_centene WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_cigna1 WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_cigna2 WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_cvs WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_centene WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_humana WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_misc WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_mutual_dean_clear_cambia_rite WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_united1 WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_united2 WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from coverage_default WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO public.current_mbi
-- SELECT DISTINCT current_mbi from sandbox WHERE current_mbi IS NOT NULL
-- ON CONFLICT DO NOTHING;
