#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/smee
PIDFILE=/var/run/smee.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
    nohup $DAEMON </dev/null &>/dev/null & echo $! > $PIDFILE
    echo "smee started"
    ;;
  stop)
    kill -9 $(cat /var/run/smee.pid)
    rm -f /var/run/smee.pid
    echo "smee stopped"
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    /etc/redhat-lsb/lsb_pidofproc -p $PIDFILE $DAEMON
    ;;
  *)
    echo "Usage: /etc/init.d/smee {start|stop|restart|force-reload|status}"  
    exit 1
    ;;
esac

exit 0
