variable "env" {}
variable "vpc_id" {}
variable "controller_subnet_ids" {}
variable "ami_id" {}
variable "instance_type" {}
variable "linux_user" {}
variable "ssh_key_name" {}
variable "iam_instance_profile" {}
variable "gold_disk_name" {}
variable "db_sec_group_id" {}
variable "deployer_ip_address" {}
variable "vpn_private_ip_address_cidr_range" {}
variable "cpm_backup_controller" {}
