# Validate environment input (dev,test,sandbox,prod)
#     Exports DEPLOYMENT_ENV (dev,east-impl,sbx-sandbox,east-prod)
# If provided, assume role for AWS region and account
#     Exports AWS_REGION and AWS_ACCOUNT
name: "Configure AB2D environment variables - Greenfield"
description: "Configure AB2D environment variables - Greenfield"
inputs:
  environment:
    description: "AB2D environment"
    required: true
  region:
    description: "AWS region"
    required: false
  account:
    description: "AWS account"
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate environment
      shell: bash
      run: |
        case "${{ inputs.environment }}" in
          dev)          ;;
          test)         ;;
          sandbox)      ;;
          prod)         ;;
          *)            echo "Invalid environment input"; exit 1 ;;
        esac

    - name: Assume AWS role  # This action adds 'AWS_REGION' to $GITHUB_ENV
      if: ${{ inputs.region != '' && inputs.account != '' }}
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        mask-aws-account-id: true
        aws-region: ${{ inputs.region }}
        role-to-assume: arn:aws:iam::${{ inputs.account }}:role/delegatedadmin/developer/ab2d-${{ inputs.environment }}-github-actions

    - name: Set AWS_ACCOUNT
      shell: bash
      if: ${{ inputs.region != '' && inputs.account != '' }}
      run: |
        echo "AWS_ACCOUNT=${{ inputs.account }}" >> $GITHUB_ENV
