name: Pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      run_tests: true
      push_image: false

  sonarqube:
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

