spring.application.name=ab2d-idr-db-importer
spring.main.web-application-type=none

## ---------------------------------------------------------------------------- DATA-SOURCE CONFIG
spring.datasource.url=jdbc:postgresql://${AB2D_DB_HOST}/${AB2D_DB_DATABASE}?sslmode=${AB2D_DB_SSL_MODE:allow}&reWriteBatchedInserts=true&ApplicationName=ab2d-idr-db-importer
spring.datasource.username=${AB2D_DB_USER}
spring.datasource.password=${AB2D_DB_PASSWORD}

## ---------------------------------------------------------------------------- S3 CONFIG
app.awsRegion=${AWS_REGION:us-east-1}
app.s3.bucket=${S3_BUCKET}

## ---------------------------------------------------------------------------- SNOWFLAKE
logging.level.net.snowflake.client.core.SFTrustManager=ERROR
app.snowflake.url=${IDR_SNOWFLAKE_URL}
app.snowflake.user=${IDR_SNOWFLAKE_USER}
app.snowflake.privateKey=${IDR_SNOWFLAKE_PRIVATE_KEY}
app.snowflake.role=${IDR_SNOWFLAKE_ROLE}
app.snowflake.warehouse=${IDR_SNOWFLAKE_WAREHOUSE}
app.snowflake.db=${IDR_SNOWFLAKE_DB:IDRC_PRD}
app.snowflake.schema=${IDR_SNOWFLAKE_SCHEMA:CMS_VDM_VIEW_MDCR_PRD}
