spring.application.name=ab2d-idr-db-importer
spring.main.web-application-type=none

## ---------------------------------------------------------------------------- DATA-SOURCE CONFIG
spring.datasource.url=jdbc:postgresql://${AB2D_DB_HOST}/${AB2D_DB_DATABASE}?sslmode=${AB2D_DB_SSL_MODE:allow}&reWriteBatchedInserts=true&ApplicationName=ab2d-idr-db-importer
spring.datasource.username=${AB2D_DB_USER}
spring.datasource.password=${AB2D_DB_PASSWORD}

## ---------------------------------------------------------------------------- S3 CONFIG
app.awsRegion=${AWS_REGION:us-east-1}
app.s3.bucket=${S3_BUCKET}
