FROM alpine:3.22

RUN apk add --no-cache curl jq bash

COPY ../fhir-test/config.json .
COPY ../fhir-test/run-fhir-test.sh .

RUN chmod +x run-fhir-test.sh

RUN addgroup fhir && adduser -D inferno -G fhir
USER inferno

ENTRYPOINT ["./run-fhir-test.sh"]