name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - sbx
          - prod
          - prod_test

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        env:
          ACCOUNT: ${{ inputs.environment == 'prod_test' && 'prod' || inputs.environment }}
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions
      - name: Deploy ECS service to run on latest image in ECR
        env:
          DEPLOYMENT_ENV: ab2d-${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}-microservice-cluster
        run: |
          echo "Deploying event service"
          aws ecs update-service --cluster "$DEPLOYMENT_ENV" --service ab2d-event-service --force-new-deployment > /dev/null
          aws ecs wait services-stable --cluster "$DEPLOYMENT_ENV" --services ab2d-event-service
