name: Deploy events GF
run-name: deploy-gf ${{ inputs.environment }} ${{ inputs.image_tag }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: AB2D environment
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      image_tag:
        description: ECR image tag (event-service-<branch>-<SHA>)
        required: true
        type: string

jobs:
  apply_tofu:
    permissions:
      contents: read
      id-token: write
    uses: cmsgov/ab2d/.github/workflows/terraform-microservices-gf.yml@main
    with:
      environment: ${{ inputs.environment }}
      events_service_image: ${{ inputs.image_tag }}
      apply: true
      ref: main
      runner: codebuild-ab2d-events-${{github.run_id}}-${{github.run_attempt}}
    secrets:
      aws_account: ${{contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.GF_NON_PROD_ACCOUNT || secrets.GF_PROD_ACCOUNT}}
