name: Unit tests and static analysis GF

on:
  workflow_call:
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-ab2d-events-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          gradle-version: 8.4

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.GF_NON_PROD_ACCOUNT }}:role/delegatedadmin/developer/ab2d-test-github-actions


      - uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token

      - name: Clean project
        run: gradle clean

      - name: Run unit tests
        run: gradle test ${RUNNER_DEBUG:+"--debug"}

      - name: SonarQube analysis
        run: |
          gradle sonar \
            -Dsonar.projectKey=ab2d-events \
            -Dsonar.host.url=https://sonarqube.cloud.cms.gov \
            -Dsonar.login=$SONAR_TOKEN

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
        timeout-minutes: 5
