version: '3'

services:
  terraform:
    image: hashicorp/terraform:1.3.7
    volumes:
      - ./:/tmp/setup
      - ./terraform:/infra
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /infra
    #user: ${UID_GID}
    environment:
      - DATA_DIR="/tmp/localstack"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  localstack:
    container_name: localstack
    image: localstack/localstack:1.3.1
    environment:
      - DEBUG=1
    ports:
      - "4566:4566"
    extra_hosts:
     - "host.docker.internal:host-gateway"
  db:
    container_name: postgres
    image: postgres:11
    command: postgres -c 'max_connections=1000'
    environment:
      - POSTGRES_DB=ab2d
      - POSTGRES_USER=ab2d
      - POSTGRES_PASSWORD=ab2d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
