variable "env" {}
variable "vpc_id" {}
variable "db_sec_group_id" {}
variable "controller_subnet_ids" {type=list(string)}
variable "ami_id" {}
variable "instance_type" {}
variable "ssh_key_name" {}
variable "node_subnet_ids" {type=list(string)}
variable "logging_bucket" {}
variable "healthcheck_url" {}
variable "iam_instance_profile" {}
variable "docker_repository_url" {}
variable "iam_role_arn" {}
variable "container_port" {default=3000}
variable "host_port" {default=80}
variable "desired_instances" {}
variable "min_instances" {}
variable "max_instances" {}
variable "autoscale_group_wait" {}
variable "gold_disk_name" {}
variable "override_task_definition_arn" {default=""}
variable "enterprise-tools-sec-group-id" {}
variable "vpn-private-sec-group-id" {}
variable "percent_capacity_increase" {default="20"}
