variable "env" {}
variable "vpc_id" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "ami_id" {}
variable "instance_type" {}
variable "linux_user" {}
variable "ssh_key_name" {}
variable "iam_instance_profile" {}
variable "jenkins_master_sec_group_id" {}
variable "vpn_private_sec_group_id" {}
variable "ec2_instance_tag" {}
