variable "env" {}
variable "autoscaling_arn" {}
variable "sns_arn" {}
variable "autoscaling_name" {}
variable "controller_server_id" {}
variable "s3_bucket_name" {}
variable "db_name" {}
variable "target_group_arn_suffix" {}
variable "loadbalancer_arn_suffix" {}