variable "ami_id" {}
variable "aws_account_number" {}
variable "bfd_keystore_file_name" {}
variable "bfd_keystore_location" {}
variable "bfd_keystore_password" {}
variable "bfd_url" {}
variable "claims_skip_billable_period_check" {}
variable "cpm_backup_worker" {}
variable "db_host" {}
variable "db_name" {}
variable "db_password" {}
variable "db_port" {}
variable "db_username" {}
variable "ec2_instance_type_worker" {}
variable "ecs_container_def_memory" {}
variable "ecs_task_def_cpu" {}
variable "ecs_task_def_memory" {}
variable "ecr_repo_aws_account" {}
variable "env" {}
variable "gold_image_name" {}
variable "hicn_hash_iter" {}
variable "hicn_hash_pepper" {}
variable "iam_instance_profile" {}
variable "iam_instance_role" {}
variable "image_version" {}
variable "new_relic_app_name" {}
variable "new_relic_license_key" {}
variable "override_task_definition_arn" {}
variable "percent_capacity_increase" {}
variable "region" {}
variable "ssh_key_name" {}
variable "ssh_username" {}
variable "vpn_private_ip_address_cidr_range" {}
variable "worker_desired_instances" {}
variable "worker_min_instances" {}
variable "worker_max_instances" {}
