name: Contracts pull request

on:
  pull_request:
    paths:
      - 'contracts/**'
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

permissions:
  contents: read
  id-token: write
defaults:
  run:
    working-directory: ./contracts

jobs:
  build:
    if: github.event.pull_request.draft == false
    secrets: inherit
    uses: ./.github/workflows/contracts-build.yml
    with:
      run_tests: true
      push_image: false

  sonarqube:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/contracts-sonarqube.yml
    secrets: inherit

