name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      module:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - sbx
          - prod
          - prod_test
      module:
        required: true
        type: choice
        options:
          - api
          - worker

env:
  # NOTE: Required checks set in repository branch protection rules/rulesets cannot be skipped
  # with the native path filtering. This regex and the 'workflow' job below is a hack to only
  # run the lengthier/costlier workflows when there are relevant files changed.
  # See https://github.com/orgs/community/discussions/44490 for a discussion.
  workflow_files_re: '^(api|common|coverage|e2e-bfd-test|e2e-test|job|src|worker)/.+$|^(pom.xml|settings.xml)$|^.github/workflows/(build|deploy|e2e-test|unit-integration-test|verify-deploy).yml$'
jobs:
  workflow:
    name: Checking workflow
    runs-on: ubuntu-24.04
    outputs:
      files: ${{ steps.workflow_files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: workflow_files
        name: Set output
        run: |-
          git diff --name-only --diff-filter=ACMRTD HEAD^ HEAD |\
            grep -P "${workflow_files_re}" \
          && echo "files=true" >> $GITHUB_OUTPUT || echo "files=" >> $GITHUB_OUTPUT
  deploy:
    needs: workflow
    if: needs.workflow.outputs.files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        env:
          ACCOUNT: ${{ inputs.environment == 'prod_test' && 'prod' || inputs.environment }}
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT_ID', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions

      - name: Deploy ECS service to run on latest image in ECR
        env:
          SERVICE_NAME: ab2d-${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}-${{ inputs.module }}
        run: |
          echo "Deploying service $SERVICE_NAME"
          aws ecs update-service --cluster "$SERVICE_NAME" --service "$SERVICE_NAME" --force-new-deployment > /dev/null
          echo "Waiting for ECS service to stabilize..."
          exit_status=1
          set +e
          while [ "$exit_status" != "0" ]; do
            aws ecs wait services-stable --cluster "$SERVICE_NAME" --services "$SERVICE_NAME"
            exit_status="$?"
            echo "Wait result: $exit_status"
          done
          set -e
          echo "✅ ECS service stabilized."
