name: API/Worker deploy
run-name: deploy ${{ inputs.module }} ${{ inputs.environment }} ${{ inputs.image_tag }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      module:
        required: true
        type: string
      image_tag:
        description: ECR image tag for selected module
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: AB2D environment used for ECR
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      module:
        description: AB2D module
        required: true
        type: choice
        options:
          - api
          - worker
          - core
      image_tag:
        description: ECR image tag for selected module (ab2d-<module>-<branch>-<SHA>)
        required: true
        type: string

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: codebuild-ab2d-${{github.run_id}}-${{github.run_attempt}}
    permissions:
      contents: read
      id-token: write
    env:
      AWS_ACCOUNT: ${{contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT}}
      AB2D_ENV: ${{ inputs.environment }}
      MODULE: ${{ inputs.module }}
      IMAGE_TAG: ${{ inputs.image_tag }}

    steps:
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/delegatedadmin/developer/ab2d-${{ env.AB2D_ENV }}-github-actions

      - name: Install Cosign
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159  # v3.9.2
  
      - name: Install tofu
        uses: cmsgov/cdap/actions/setup-tenv@8343fb96563ce4b74c4dececee9b268f42bd4a40

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Tofu plan and apply - Worker
        working-directory: ops/services/30-worker/
        if: ${{ env.MODULE == 'worker' }}
        run: |
          tofu init -var=parent_env=$AB2D_ENV -reconfigure
          tofu workspace select -var=parent_env=$AB2D_ENV -or-create=true $AB2D_ENV
          tofu plan -var=worker_service_image_tag="$IMAGE_TAG" -out=tfplan
          tofu apply -input=false tfplan 

      - name: Tofu plan and apply - API
        working-directory: ops/services/30-api/
        if: ${{ env.MODULE == 'api' }}
        run: |
          tofu init -var=parent_env=$AB2D_ENV -reconfigure
          tofu workspace select -var=parent_env=$AB2D_ENV -or-create=true $AB2D_ENV
          tofu plan -var=api_service_image_tag="$IMAGE_TAG" -out=tfplan
          tofu apply -input=false tfplan

      - name: Tofu plan and apply - Core
        working-directory: ops/services/10-core/
        if: ${{ env.MODULE == 'core' }}
        run: |
          tofu init -var=parent_env=$AB2D_ENV -reconfigure
          tofu workspace select -var=parent_env=$AB2D_ENV -or-create=true $AB2D_ENV
          tofu plan -out=tfplan
