name: deploy-lambdas

on:
  push:
    branches:
      - lambda-tf-workflow
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  publish_lambdas:
    uses: cmsgov/ab2d-lambdas/.github/workflows/publish-lambdas.yml@update-publish-lamda-workflow
    with:
      environment: dev
    if: true

  deploy:
    runs-on: self-hosted
    needs: publish_lambdas
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      AWS_REGION: ${{ vars.AWS_REGION }}
      DEPLOYMENT_ENV: ${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test publish lambdas
        run: |
          echo "test"
          echo "build_version=${{ needs.publish_lambdas.outputs.build_version }}"
        

#      - name: Assume role in AB2D account for this environment
#        uses: aws-actions/configure-aws-credentials@v3
#        env:
#          ACCOUNT: ${{ inputs.environment }}
#        with:
#          aws-region: ${{ vars.AWS_REGION }}
#          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT_ID', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions
#
#
