name: Libs build
run-name: Build-libraries

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  id-token: write
defaults:
  run:
    working-directory: ./libs

jobs:
  build:
    runs-on: codebuild-ab2d-non-prod-${{github.run_id}}-${{github.run_attempt}}
    env:
      AWS_ACCOUNT: ${{ secrets.NON_PROD_ACCOUNT }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0

      - name: Set up JDK
        uses: actions/setup-java@v3 #TODO: Update to Node24
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Assume role in target account
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/delegatedadmin/developer/ab2d-dev-github-actions

      - name: Set env vars from AWS params
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token

      - name: Build and test libraries
        run: ./gradlew clean test --info -b build.gradle

      - name: Build JARs
        run: ./gradlew jar --warn -b build.gradle
