name: microservices-deploy
run-name: microservices-deploy ${{ inputs.apply && 'apply' || 'plan' }}  ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
      environment:
        required: true
        type: string
      contracts_service_image:
        type: string
        required: false
      events_service_image:
        type: string
        required: false

  workflow_dispatch:  # Manual trigger with dropdowns
    inputs:
      apply:
        description: "Apply tofu?"
        required: false
        type: boolean
        default: false
      environment:
        description: "AB2D environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      contracts_service_image:
        description: "ab2d-contracts image"
        type: string
        required: false
      events_service_image:
        description: "ab2d-events image"
        type: string
        required: false

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    strategy:
      matrix:
        include:
        - service: contracts
          dir: ops/services/20-contracts/
          image_var: contracts_service_image_tag
          image: ${{inputs.contracts_service_image }}
        - service: events
          dir: ops/services/20-events/
          image_var: events_service_image_tag
          image: ${{ inputs.events_service_image }}

    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-ab2d-${{ contains(fromJSON('["dev", "test"]'), inputs.environment) && 'non-prod' || 'prod'}}-${{github.run_id}}-${{github.run_attempt}}
    env:
      AWS_ACCOUNT: ${{ secrets.aws_account || (contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT) }}
      AB2D_ENV: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Assume role in AB2D account for this environment
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/delegatedadmin/developer/ab2d-${{ env.AB2D_ENV }}-github-actions

      - name: Install Cosign
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159  # v3.9.2
    
      - name: Install tofu
        uses: cmsgov/cdap/actions/setup-tenv@f4c14d47cc20e7f6de9112d7155af1213c9bca5a

      - name: Skipping ${{ matrix.service }}
        if: ${{ matrix.image == '' }}
        run: |
          echo "**Skipping ${{ matrix.service }} plan/apply**" >> $GITHUB_STEP_SUMMARY

      - name: Tofu init & plan
        if: ${{ matrix.image != '' }}
        working-directory: ${{ matrix.dir }}
        run: |
          tofu init -var=parent_env=$AB2D_ENV -reconfigure
          tofu workspace select -var=parent_env=$AB2D_ENV -or-create=true $AB2D_ENV
          TOFU_VARS="-var=${{ matrix.image_var }}=${{ matrix.image }}"
          echo "**${{ matrix.image_var }} -> ${{ matrix.image }}**" >> $GITHUB_STEP_SUMMARY
          tofu plan $TOFU_VARS -out=tfplan

      - name: Tofu apply
        if: ${{ inputs.apply == true && matrix.image != '' }}
        working-directory: ${{ matrix.dir }}
        run: |
          tofu apply -input=false tfplan 
