name: 60-monitors
run-name: "[${{ github.event_name == 'push' && 'APPLY' || 'PLAN' }}] 60-monitors → ${{ github.event_name == 'push' && github.ref_name || github.head_ref }}"

on:
  push:
    branches:
      - main
    paths:
      - "ops/services/60-monitors/**"
  pull_request:
    branches:
      - main
    paths:
      - "ops/services/60-monitors/**"

concurrency:
  group: tofu-plan-or-apply

permissions:
  contents: read
  id-token: write

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: codebuild-ab2d-non-prod-${{ github.run_id }}-${{ github.run_attempt }}
    outputs:
      apply: ${{ steps.check.outputs.apply }}
      branch: ${{ steps.check.outputs.branch }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
      - id: check
        run: |
          echo "apply=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}" >> $GITHUB_OUTPUT
          echo "branch=${{ github.head_ref || github.ref }}" >> $GITHUB_OUTPUT

  dev:
    needs: setup
    uses: ./.github/workflows/tofu-run.yml
    with:
      service: "60-monitors"
      environment: "dev"
      apply: ${{ needs.setup.outputs.apply }}
      branch: ${{ needs.setup.outputs.branch }}
    secrets: inherit

  test:
    needs: [setup, dev]
    uses: ./.github/workflows/tofu-run.yml
    with:
      service: "60-monitors"
      environment: "test"
      apply: ${{ needs.setup.outputs.apply }}
      branch: ${{ needs.setup.outputs.branch }}
    secrets: inherit

  sandbox:
    needs: [setup, test]
    uses: ./.github/workflows/tofu-run.yml
    with:
      service: "60-monitors"
      environment: "sandbox"
      apply: ${{ needs.setup.outputs.apply }}
      branch: ${{ needs.setup.outputs.branch }}
    secrets: inherit

  prod:
    needs: [setup, sandbox]
    uses: ./.github/workflows/tofu-run.yml
    with:
      service: "60-monitors"
      environment: "prod"
      apply: ${{ needs.setup.outputs.apply }}
      branch: ${{ needs.setup.outputs.branch }}
    secrets: inherit
