name: promote

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      module:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - sbx
          - prod
          - prod-test
      module:
        required: true
        type: choice
        options:
          - api
          - worker

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.MGMT_ACCOUNT_ID }}:role/delegatedadmin/developer/ab2d-mgmt-github-actions
      - name: Retag images in ECR
        env:
          DEPLOYMENT_ENV: ${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}
        run: |
          REPO="ab2d_${{ inputs.module }}"
          SHA_SHORT=$(git rev-parse --short HEAD)

          # Get the manifest of the image pushed for latest commit to main
          MANIFEST=$(aws ecr batch-get-image --repository-name "$REPO" --image-ids imageTag=main-$SHORT_SHA --output text --query 'images[].imageManifest')

          # Add the tag for sha
          if ! OUT=$(2>&1 aws ecr put-image --repository-name "$REPO" --image-tag "ab2d-$DEPLOYMENT_ENV-$SHA_SHORT" --image-manifest "$MANIFEST"); then
            if echo "$OUT" | grep ImageAlreadyExistsException > /dev/null; then
              echo "Image for main-$SHORT_SHA has already been tagged with ab2d-$DEPLOYMENT_ENV-$SHA_SHORT"
            else
              >&2 echo "$OUT"
              exit 1
            fi
          fi

          # Add the tag for latest
          if ! OUT=$(2>&1 aws ecr put-image --repository-name "$REPO" --image-tag "ab2d-$DEPLOYMENT_ENV-latest" --image-manifest "$MANIFEST"); then
            if echo "$OUT" | grep ImageAlreadyExistsException > /dev/null; then
              echo "Image for main-$SHORT_SHA has already been tagged with ab2d-$DEPLOYMENT_ENV-latest"
            else
              >&2 echo "$OUT"
              exit 1
            fi
          fi
