name: promote

on:
  release:
    types: [released]
  push:
    # branches:
    #   - ""

jobs:
  promote:
    uses: ./.github/workflows/promote.yml
    secrets: inherit

  promote-sandbox:
    needs: promote
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: sbx
      module: ${{ inputs.module }}
    secrets: inherit

  promote-prod:
    needs: promote
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      module: ${{ inputs.module }}
    secrets: inherit

  promote-prod-test:
    needs: promote
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod-test
      module: ${{ inputs.module }}
    secrets: inherit
