name: promote

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      module:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - sbx
          - prod
          - prod_test
      module:
        required: true
        type: choice
        options:
          - api
          - worker

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.MGMT_ACCOUNT_ID }}:role/delegatedadmin/developer/ab2d-mgmt-github-actions

      - name: Set environment variables
        env:
          DEPLOYMENT_ENV: ${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}
        run: |
          if [ "${{ inputs.environment }}" == "prod_test" ]; then
            echo "TAG_PREFIX=ab2d-prod-test" >> $GITHUB_ENV
          else
            echo "TAG_PREFIX=ab2d-$DEPLOYMENT_ENV" >> $GITHUB_ENV

      - name: Retag images in ECR
        env:
          ECR_REPO_DOMAIN: ${{ secrets.MGMT_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          ECR_REPO: ab2d_${{ inputs.module }}
        run: |
          SHA_SHORT="$(git rev-parse --short HEAD)"
          TOKEN="$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken')"
          CONTENT_TYPE="application/vnd.docker.distribution.manifest.v2+json"

          echo "Getting the manifest of the image tagged main-$SHA_SHORT"
          MANIFEST="$(curl -sS -H "Authorization: Basic $TOKEN" -H "Accept: $CONTENT_TYPE" "https://$ECR_REPO_DOMAIN/v2/$ECR_REPO/manifests/main-$SHA_SHORT")"

          SHA_TAG="$TAG_PREFIX-$SHA_SHORT"
          echo "Adding the $SHA_TAG tag to main-$SHA_SHORT image"
          curl -sS -X PUT -H "Authorization: Basic $TOKEN" -H "Content-Type: $CONTENT_TYPE" -d "$MANIFEST" "https://$ECR_REPO_DOMAIN/v2/$ECR_REPO/manifests/$SHA_TAG"

          LATEST_TAG="$TAG_PREFIX-latest"
          echo "Adding the $LATEST_TAG tag to main-$SHA_SHORT image"
          curl -sS -X PUT -H "Authorization: Basic $TOKEN" -H "Content-Type: $CONTENT_TYPE" -d "$MANIFEST" "https://$ECR_REPO_DOMAIN/v2/$ECR_REPO/manifests/$LATEST_TAG"
