name: push to main

on:
  push:
    branches:
      - main
    paths-ignore:
      - libs/**
      - lambdas/**
      - contracts/**
      - events/**

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy-api:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: test
      module: api
    secrets: inherit
  build-deploy-worker:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: test
      module: worker
    secrets: inherit
  e2e-test:
    needs: [ build-deploy-api, build-deploy-worker ]
    uses: ./.github/workflows/e2e-test.yml
    with:
      environment: test
    secrets: inherit
  e2e-bfd-test:
    needs: [ e2e-test ]
    uses: ./.github/workflows/e2e-bfd-test.yml
    with:
      environment: test
    secrets: inherit
  fhir-test:
    needs: [ build-deploy-api, build-deploy-worker ]
    uses: ./.github/workflows/fhir-test.yml
    with:
      environment: test
    secrets: inherit
  unit_integration_tests:
    uses: ./.github/workflows/unit-integration-test.yml
    with:
      skip_sonarqube: false
      skip_integration_tests: false
    secrets: inherit
