name: push to main

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build-deploy-api:
    uses: ./.github/workflows/build-deploy-gf.yml
    with:
      environment: test
      module: api
    secrets: inherit
  build-deploy-worker:
    uses: ./.github/workflows/build-deploy-gf.yml
    with:
      environment: test
      module: worker
    secrets: inherit
  e2e-bfd-test:
    needs: [ build-deploy-api, build-deploy-worker ]
    uses: ./.github/workflows/e2e-bfd-test-gf.yml
    with:
      environment: test
    secrets: inherit
  e2e-test:
    needs: [ e2e-bfd-test ]
    uses: ./.github/workflows/e2e-test-gf.yml
    with:
      environment: test
    secrets: inherit
