name: push to main

on:
  push:
    branches:
      - main

jobs:
  build-deploy-api:
    uses: ./.github/workflows/build-deploy-gf.yml
    with:
      environment: test
      module: api
    secrets: inherit
  build-deploy-worker:
    uses: ./.github/workflows/build-deploy-gf.yml
    with:
      environment: test
      module: worker
    secrets: inherit
  e2e-test:
    needs: [build-deploy-api, build-deploy-worker]
    uses: ./.github/workflows/e2e-test.yml
    with:
      environment: test
    secrets: inherit
