name: push to main

on:
  push:
    branches:
      - main

jobs:
  build-api:
    uses: ./.github/workflows/build.yml
    with:
      environment: test
      module: api
    secrets: inherit
  build-worker:
    uses: ./.github/workflows/build.yml
    with:
      environment: test
      module: worker
    secrets: inherit
  deploy-api:
    needs: build-api
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      module: api
    secrets: inherit
  deploy-worker:
    needs: build-worker
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      module: worker
    secrets: inherit
  e2e-test:
    needs: [deploy-api, deploy-worker]
    uses: ./.github/workflows/e2e-test.yml
    with:
      environment: test
    secrets: inherit
