name: Snyk monitor

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        description: 'Branch to scan'
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  snyk-monitor:
    name: 'Snyk monitor for AB2D'
    uses: CMSGov/CDAP/.github/workflows/snyk-monitor.yml@ab2d-snyk-testing
    with:
      app: ab2d
      ref: ${{ inputs.branch }}
      cli_args: "--all-projects --exclude=e2e-bfd-test,e2e-test,fhir-test,common,coverage,job,libs,ops,local-dev,scripts"
    secrets:
      PROD_ACCOUNT: ${{ secrets.PROD_ACCOUNT }}
