
name: start-job-gf
run-name: start-job-gf ${{ inputs.environment }} ${{ inputs.contractNumber }}

on:
  push:
    branches: ["ephemeral-e2e"]

  workflow_dispatch: # Allow manual trigger
    inputs:
      environment:
        description: 'AB2D environment'
        type: string
        required: true
        default: 'test'
      contractNumber:
        description: 'Contract to start a job for'
        type: string
        required: true
        default: 'Z0001'
      fhirVersion:
        description: 'FHIR version'
        type: choice
        options:
          - STU3
          - R4
        default: STU3
      since:
        description: 'Since date to use for a job. The earliest accepted date is 2020-02-13T00:00:00.000-05:00'
        type: string
        required: true
      until:
        description: 'Until date to use for a job. Accepted date format for V2 is 2020-02-13T00:00:00.000-05:00'
        type: string
        required: false
      apiUrlPrefix:
        description: 'Origin of request for a job. May correspond to actual AB2D API URL or not. Leave blank to populate default value.'
        type: string
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  start-job:
    runs-on: codebuild-ab2d-${{github.run_id}}-${{github.run_attempt}}

    env:
#      CONTRACT_NUMBER: ${{ inputs.contractNumber }}
      CONTRACT_NUMBER: 'Z0001'
      FHIR_VERSION: 'R4'
#      FHIR_VERSION: ${{ inputs.fhirVersion }}
#      SINCE: ${{ inputs.since }}
      SINCE: '2022-01-01 05:00:00+00'
      UNTIL: '2025-07-07 05:00:00+00'
#      UNTIL: ${{ inputs.until }}
      API_URL_PREFIX: ${{ inputs.apiUrlPrefix }}
#      AB2D_ENV: ${{ inputs.environment }}
      AB2D_ENV: '6755-dev'

#      AWS_ACCOUNT: ${{contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set environment-specific variables
        run: |
          ENV=$(echo "$AB2D_ENV" | sed 's/^[0-9]\+-//')
          echo "ENV=$ENV" >> $GITHUB_ENV
          
          AWS_ACCOUNT=${{contains(fromJSON('["dev", "test"]'), env.ENV) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT}}
          echo "AWS_ACCOUNT=$AWS_ACCOUNT" 
          
          if [ "$ENV" == "dev" ]; then
            DEFAULT_API_URL_PREFIX="https://dev.ab2d.cms.gov"
          elif [ "$ENV" == "test" ]; then
            DEFAULT_API_URL_PREFIX="https://test.ab2d.cms.gov"
          elif [ "$ENV" == "sandbox" ]; then
            DEFAULT_API_URL_PREFIX="https://sandbox.ab2d.cms.gov"
          elif [ "$ENV" == "prod" ]; then
            DEFAULT_API_URL_PREFIX="https://api.ab2d.cms.gov" 
          else
            echo "Invalid environment: $ENVIRONMENT"
            exit 1
          fi
   
          echo "DEFAULT_API_URL_PREFIX=${DEFAULT_API_URL_PREFIX}" >> $GITHUB_ENV

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/delegatedadmin/developer/ab2d-${{ env.ENV }}-github-actions

      - name: Set env vars from AWS params in AB2D account
        uses: ./.github/workflows/actions/set-database-params
        with:
          aws_region: ${{ vars.AWS_REGION }}
          environment: ${{ env.AB2D_ENV }}

      - name: Install psql
        run: |
          sudo dnf install postgresql16 -y

      - name: Insert record
        run: |
          set -e
          export JOB_ID=$(uuidgen)

          SQL_GET_ORGANIZATION=$(envsubst < .github/workflows/resources/get-organization.sql)
          export ORGANIZATION=$(psql -t --command="${SQL_GET_ORGANIZATION}" | head -n 1 | xargs | tr -d '\r')
          if [ -z "${ORGANIZATION}" ]; then
            echo "Unable to retrieve organization"
            exit 1
          fi

          if [[ ${FHIR_VERSION} = "R4" ]]; then
            export UNTIL="'${UNTIL}'"
          else
            export UNTIL="null"
          fi

          if [ -z "${API_URL_PREFIX}" ]; then
            export API_URL_PREFIX=${DEFAULT_API_URL_PREFIX}
          fi

          SQL_INSERT_RECORD=$(envsubst < .github/workflows/resources/insert-record.sql)
          psql -t --command="${SQL_INSERT_RECORD}"
          echo "Inserted record with job UUID = $JOB_ID"
