name: temporary-testing-gf
run-name: testing ${{ inputs.environment }}

on:
  #  push:
  #    branches:
  #      - terraform-gf-WIP

  workflow_call:
    inputs:
      environment:
        required: true
        type: string  # Choice not allowed in workflow_call, so using string
  workflow_dispatch: # Manual trigger with dropdowns
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod

jobs:

  testing:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-ab2d-${{github.run_id}}-${{github.run_attempt}}

    steps:
      - name: Set AB2D_ENV
        uses: cmsgov/ab2d/actions/configure-ab2d-env-gf@terraform-gf-WIP
        with:
          environment: ${{ inputs.environment }}
          region: ${{ vars.AWS_REGION }}
          account: ${{contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT}}

      - name: Verify
        run: |
          echo "AB2D env = ${AB2D_ENV}"
          

