name: terraform-gf
run-name: tf ${{ inputs.apply && 'apply' || 'plan' }} ${{ inputs.service }} ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
      environment:
        required: true
        type: string  # Choice not allowed in workflow_call, so using string
      ops_branch:
        required: false
        type: string
        default: 'main'
      service:
        required: true
        type: string  # Same as above

  workflow_dispatch:  # Manual trigger with dropdowns
    inputs:
      apply:
        required: false
        type: boolean
        default: false
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      ops_branch:
        required: false
        type: string
        default: 'main'
      service:
        required: true
        type: choice
        options:
          - api
          - api_gateway
          - bfd_insights
          - controller
          - core
          - eventbridge
          - lambda
          - microservices
          - web
          - worker

jobs:
  terraform:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-ab2d-${{github.run_id}}-${{github.run_attempt}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Assume role in AB2D account for this environment
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT}}:role/delegatedadmin/developer/ab2d-${{ inputs.environment }}-github-actions

      - name: Install tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.0-beta1

      - name: Tofu Init & Plan
        working-directory: ops/services/20-microservices/
        run: |
          tofu init -var=parent_env=dev -reconfigure
          tofu workspace select -var=parent_env=dev -or-create=true dev
          tofu plan -var=contracts_service_image_tag=contracts-service-more-workflows-gf -out=tfplan


      - name: Tofu Apply
        if: ${{ inputs.apply == true }}
        working-directory: terraform/services/${{ inputs.service }}/
        run: |
          tofu apply -input=false tfplan 
          
