name: Update Gold Disk

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        description: "Branch to run this workflow on"
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - sbx
          - prod-test
          - prod

jobs:
  update-gold-disk:
    runs-on: self-hosted

    steps:

      - name: Get AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            OPS_GITHUB_TOKEN=/ci/github/token


      - name: Checkout AB2D-Ops Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'cmsgov/ab2d-ops'
          token: ${{ env.OPS_GITHUB_TOKEN }}
          ref: ${{ inputs.ops_branch }}

      - name: Set Environment Variables
        run: |
          ENVIRONMENT="${{ inputs.environment }}"
          
          # Map inputs.environment to the expected PARENT_ENV
          case "$ENVIRONMENT" in
            dev) PARENT_ENV="ab2d-dev" ;;
            test) PARENT_ENV="ab2d-east-impl" ;;
            sbx) PARENT_ENV="ab2d-sbx-sandbox" ;;
            prod-test) PARENT_ENV="ab2d-east-prod-test" ;;
            prod) PARENT_ENV="ab2d-east-prod" ;;
            *) echo "Invalid environment input"; exit 1 ;;
          esac
          
          # Map PARENT_ENV to correct AWS account
          case "$PARENT_ENV" in
            "ab2d-east-impl") ACCOUNT="test" ;;
            "ab2d-dev") ACCOUNT="dev" ;;
            "ab2d-sbx-sandbox") ACCOUNT="sbx" ;;
            "ab2d-east-prod" | "ab2d-east-prod-test") ACCOUNT="prod" ;;
            *) echo "Invalid PARENT_ENV"; exit 1 ;;
          esac
          
          echo "PARENT_ENV=$PARENT_ENV" >> $GITHUB_ENV
          echo "ACCOUNT=$ACCOUNT" >> $GITHUB_ENV

      - name: Assume Role in AB2D Account
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT_ID', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions

      - name: Run Update Gold Disk Script
        run: |
          chmod +x scripts/deployment/update-gold-disk.sh
          scripts/deployment/update-gold-disk.sh --cms_env $PARENT_ENV --cloud_tamer false
