name: Update Gold Disk

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        description: "Branch to run this workflow on (defaults to main)"
      environment:
        required: false
        type: choice
        options:
          - dev
          - test
          - sbx
          - prod-test
          - prod
        description: "Deployment environment (defaults to dev on pull request)"

jobs:
  update-gold-disk:
    runs-on: self-hosted

    steps:
      - name: Get AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            OPS_GITHUB_TOKEN=/ci/github/token

      - name: Determine Branch and Environment
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ENVIRONMENT="dev"
            BRANCH="${{ github.head_ref }}"
          else
            ENVIRONMENT="${{ github.event.inputs.environment || 'dev' }}"
            BRANCH="${{ github.event.inputs.branch || 'main' }}"
          fi

          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Checkout AB2D-Ops Repository
        uses: actions/checkout@v4
        with:
          repository: 'cmsgov/ab2d-ops'
          token: ${{ env.OPS_GITHUB_TOKEN }}

      - name: Set PARENT_ENV and AWS Account
        run: |
          case "$ENVIRONMENT" in
            dev) PARENT_ENV="ab2d-dev" ;;
            test) PARENT_ENV="ab2d-east-impl" ;;
            sbx) PARENT_ENV="ab2d-sbx-sandbox" ;;
            prod-test) PARENT_ENV="ab2d-east-prod-test" ;;
            prod) PARENT_ENV="ab2d-east-prod" ;;
            *) echo "Invalid environment input: $ENVIRONMENT"; exit 1 ;;
          esac

          case "$PARENT_ENV" in
            "ab2d-east-impl") ACCOUNT="test" ;;
            "ab2d-dev") ACCOUNT="dev" ;;
            "ab2d-sbx-sandbox") ACCOUNT="sbx" ;;
            "ab2d-east-prod" | "ab2d-east-prod-test") ACCOUNT="prod" ;;
            *) echo "Invalid PARENT_ENV"; exit 1 ;;
          esac

          # Now that ACCOUNT is defined, use it to fetch the secret
          AWS_ACCOUNT_NUMBER="${{ secrets[format('{0}_ACCOUNT_ID', ACCOUNT)] }}"

          echo "PARENT_ENV=$PARENT_ENV" >> $GITHUB_ENV
          echo "ACCOUNT=$ACCOUNT" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_NUMBER=$AWS_ACCOUNT_NUMBER" >> $GITHUB_ENV

      - name: Assume Role in AB2D Account
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT_ID', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions

      - name: Run Update Gold Disk Script
        run: |
          chmod +x scripts/deployment/update-gold-disk.sh
          scripts/deployment/update-gold-disk.sh --cms_env $PARENT_ENV --cloud_tamer false
