name: Verify deployment

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      module:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - sbx
          - prod

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Assume role in AB2D Management account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.MGMT_ACCOUNT_ID }}:role/delegatedadmin/developer/ab2d-mgmt-github-actions

      - name: Set environment-specific variables
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "SECRET_ID=ab2d/ab2d-east-impl/jenkins-verify-api" >> $GITHUB_ENV
            echo "BASE_URL=https://impl.ab2d.cms.gov" >> $GITHUB_ENV
            echo "EXPORT_URL=https://impl.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "dev" ]; then
            echo "SECRET_ID=ab2d/ab2d-dev/jenkins-verify-basic-auth" >> $GITHUB_ENV
            echo "BASE_URL=https://dev.ab2d.cms.gov" >> $GITHUB_ENV
            echo "EXPORT_URL=https://dev.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "test" ]; then
            echo "SECRET_ID=ab2d/ab2d-east-impl/jenkins-verify-api" >> $GITHUB_ENV
            echo "BASE_URL=https://impl.ab2d.cms.gov" >> $GITHUB_ENV
            echo "EXPORT_URL=https://impl.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "sbx" ]; then
            echo "SECRET_ID=ab2d/ab2d-sbx-sandbox/jenkins-verify-basic-auth" >> $GITHUB_ENV
            echo "BASE_URL=https://sbx.ab2d.cms.gov" >> $GITHUB_ENV
            echo "EXPORT_URL=https://sbx.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "prod" ]; then
            echo "SECRET_ID=ab2d/ab2d-east-prod/jenkins-verify-basic-auth" >> $GITHUB_ENV
            echo "BASE_URL=https://api.ab2d.cms.gov" >> $GITHUB_ENV
            echo "EXPORT_URL=https://api.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
          else
            echo "Invalid environment: ${{ inputs.environment }}"
            exit 1
          fi

      - name: Set script file based on environment
        run: echo "script=./scripts/verify-deployment.sh" >> $GITHUB_ENV

      - name: Run deployment verification script
        run: |
          chmod +x $script
          ./$script
        env:
          script: ${{ env.script }}
