DROP SEQUENCE IF EXISTS event_bene_coverage_search_status_change_seq;
CREATE SEQUENCE IF NOT EXISTS public.event_bene_coverage_search_status_change_seq START 1 INCREMENT BY 50;

DROP SEQUENCE IF EXISTS contract_seq;
CREATE SEQUENCE IF NOT EXISTS contract_seq INCREMENT BY 50 START WITH 1;

DROP SEQUENCE IF EXISTS role_seq;
CREATE SEQUENCE IF NOT EXISTS role_seq INCREMENT BY 50 START WITH 1;

DROP SEQUENCE IF EXISTS job_seq;
CREATE SEQUENCE IF NOT EXISTS public.job_seq INCREMENT BY 50 START WITH 1;

DROP SEQUENCE IF EXISTS job_output_seq;
CREATE SEQUENCE IF NOT EXISTS public.job_output_seq INCREMENT BY 50 START WITH 1;
